from __future__ import annotations

from enum import Enum


class Action(str, Enum):
    BILLING_PERIOD_FINALIZE = "BILLING_PERIOD_FINALIZE"
    BILLING_PERIOD_LOCK = "BILLING_PERIOD_LOCK"
    BILLING_PERIOD_REOPEN = "BILLING_PERIOD_REOPEN"
    INVOICE_ISSUE = "INVOICE_ISSUE"
    INVOICE_ADJUST = "INVOICE_ADJUST"
    PAYMENT_APPLY = "PAYMENT_APPLY"
    CREDIT_NOTE_CREATE = "CREDIT_NOTE_CREATE"
    PAYOUT_EXPORT_CREATE = "PAYOUT_EXPORT_CREATE"
    PAYOUT_EXPORT_CONFIRM = "PAYOUT_EXPORT_CONFIRM"
    ACCOUNTING_EXPORT_CREATE = "ACCOUNTING_EXPORT_CREATE"
    ACCOUNTING_EXPORT_CONFIRM = "ACCOUNTING_EXPORT_CONFIRM"
    DOCUMENT_ACKNOWLEDGE = "DOCUMENT_ACKNOWLEDGE"
    DOCUMENT_FINALIZE = "DOCUMENT_FINALIZE"
    DOCUMENT_SIGN_REQUEST = "DOCUMENT_SIGN_REQUEST"
    DOCUMENT_SEND_FOR_SIGNING = "DOCUMENT_SEND_FOR_SIGNING"
    DOCUMENT_FINALIZE_WITH_SIGNATURE = "DOCUMENT_FINALIZE_WITH_SIGNATURE"
    DOCUMENT_VOID_AFTER_SIGNING = "DOCUMENT_VOID_AFTER_SIGNING"
    CLOSING_PACKAGE_ACK = "CLOSING_PACKAGE_ACK"
    CLOSING_PACKAGE_FINALIZE = "CLOSING_PACKAGE_FINALIZE"
    CRM_CLIENT_MANAGE = "CRM_CLIENT_MANAGE"
    CRM_CONTRACT_MANAGE = "CRM_CONTRACT_MANAGE"
    CRM_TARIFF_MANAGE = "CRM_TARIFF_MANAGE"
    CRM_SUBSCRIPTION_MANAGE = "CRM_SUBSCRIPTION_MANAGE"
    CRM_FEATURE_TOGGLE = "CRM_FEATURE_TOGGLE"


__all__ = ["Action"]
