// generated catalog
export type SubscriptionAudience = "CLIENT" | "PARTNER";
export type SubscriptionPlanCode = "CLIENT_FREE_TRIAL"|"CLIENT_START"|"CLIENT_SMART"|"CLIENT_BUSINESS"|"CLIENT_PRO"|"CLIENT_ENTERPRISE"|"PARTNER_STARTER"|"PARTNER_TEAM"|"PARTNER_AGENCY"|"PARTNER_SCALE"|"PARTNER_ENTERPRISE";
export type CustomerType = "INDIVIDUAL" | "SOLE_PROPRIETOR" | "LEGAL_ENTITY";
export type SubscriptionState = "NONE"|"TRIAL_PENDING"|"TRIAL_ACTIVE"|"PAYMENT_PENDING"|"PAYMENT_PROCESSING"|"PAYMENT_FAILED"|"ACTIVE"|"PAST_DUE"|"EXPIRED"|"CANCELED";
export type SubscriptionPlan={code:SubscriptionPlanCode;audience:SubscriptionAudience;title:string;shortTitle:string;badge?:string;isFeatured?:boolean;isTrial?:boolean;isEnterprise?:boolean;availableCustomerTypes?:CustomerType[];monthlyPrice?:number|null;yearlyPrice?:number|null;yearlyDiscountText?:string|null;description:string;bullets:string[];limits:{users?:number|null;cards?:number|null;fleetUnits?:number|null;apiCallsPerMonth?:number|null;documentsPerMonth?:number|null};modules:{dashboard:boolean;documents:boolean;analytics:boolean;cards:boolean;expenses:boolean;reports:boolean;limits:boolean;users:boolean;fleet:boolean;logistics:boolean;stationsMap:boolean;support:boolean;apiAccess:boolean;webhooks:boolean;whiteLabel?:boolean;payouts?:boolean;crmExport?:boolean};supportTier:"community"|"standard"|"priority"|"dedicated"};
const ALL_CUSTOMER_TYPES: CustomerType[]=["INDIVIDUAL","SOLE_PROPRIETOR","LEGAL_ENTITY"];
export const SUBSCRIPTION_CATALOG: SubscriptionPlan[]=[
{code:"CLIENT_FREE_TRIAL",audience:"CLIENT",title:"Client Free Trial",shortTitle:"Trial",badge:"Trial",isTrial:true,monthlyPrice:0,yearlyPrice:null,yearlyDiscountText:null,description:"Limited access trial plan",bullets:["No payment on activation","Basic dashboard and documents","Limited users/cards"],limits:{users:1,cards:1,documentsPerMonth:20},modules:{dashboard:true,documents:true,analytics:true,cards:false,expenses:true,reports:false,limits:true,users:false,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:false,webhooks:false},supportTier:"community",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"CLIENT_START",audience:"CLIENT",title:"Client Start",shortTitle:"Start",monthlyPrice:2900,yearlyPrice:29000,yearlyDiscountText:"-17% yearly",description:"Starter plan",bullets:["Up to 20 cards","Core docs and spend control"],limits:{users:2,cards:20,documentsPerMonth:200},modules:{dashboard:true,documents:true,analytics:false,cards:true,expenses:true,reports:false,limits:true,users:false,fleet:false,logistics:false,stationsMap:true,support:true,apiAccess:false,webhooks:false},supportTier:"standard",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"CLIENT_SMART",audience:"CLIENT",title:"Client Smart",shortTitle:"Smart",isFeatured:true,badge:"Popular",monthlyPrice:5900,yearlyPrice:59000,yearlyDiscountText:"-17% yearly",description:"For growing business",bullets:["Analytics basic","Fleet basics","More users"],limits:{users:5,cards:60,fleetUnits:15,documentsPerMonth:700},modules:{dashboard:true,documents:true,analytics:true,cards:true,expenses:true,reports:true,limits:true,users:true,fleet:true,logistics:false,stationsMap:true,support:true,apiAccess:false,webhooks:false},supportTier:"standard",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"CLIENT_BUSINESS",audience:"CLIENT",title:"Client Business",shortTitle:"Business",monthlyPrice:9900,yearlyPrice:99000,yearlyDiscountText:"-17% yearly",description:"SME plan",bullets:["Operational modules","Reports + analytics","Team management"],limits:{users:15,cards:150,fleetUnits:60,documentsPerMonth:2000},modules:{dashboard:true,documents:true,analytics:true,cards:true,expenses:true,reports:true,limits:true,users:true,fleet:true,logistics:true,stationsMap:true,support:true,apiAccess:false,webhooks:false},supportTier:"priority",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"CLIENT_PRO",audience:"CLIENT",title:"Client Pro",shortTitle:"Pro",monthlyPrice:16900,yearlyPrice:169000,yearlyDiscountText:"-17% yearly",description:"Advanced operations",bullets:["API access","Webhooks","High limits"],limits:{users:40,cards:500,fleetUnits:200,apiCallsPerMonth:200000,documentsPerMonth:8000},modules:{dashboard:true,documents:true,analytics:true,cards:true,expenses:true,reports:true,limits:true,users:true,fleet:true,logistics:true,stationsMap:true,support:true,apiAccess:true,webhooks:true,crmExport:true},supportTier:"priority",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"CLIENT_ENTERPRISE",audience:"CLIENT",title:"Client Enterprise",shortTitle:"Enterprise",isEnterprise:true,monthlyPrice:null,yearlyPrice:null,yearlyDiscountText:"Custom contract",description:"Large organizations",bullets:["White-label options","Dedicated support","Custom SLA"],limits:{users:null,cards:null,fleetUnits:null,apiCallsPerMonth:null,documentsPerMonth:null},modules:{dashboard:true,documents:true,analytics:true,cards:true,expenses:true,reports:true,limits:true,users:true,fleet:true,logistics:true,stationsMap:true,support:true,apiAccess:true,webhooks:true,whiteLabel:true,payouts:true,crmExport:true},supportTier:"dedicated",availableCustomerTypes:ALL_CUSTOMER_TYPES},
{code:"PARTNER_STARTER",audience:"PARTNER",title:"Partner Starter",shortTitle:"Starter",monthlyPrice:4900,yearlyPrice:49000,yearlyDiscountText:"-17% yearly",description:"Single operator onboarding",bullets:["Basic partner cabinet","Low service volume"],limits:{users:1,apiCallsPerMonth:20000},modules:{dashboard:true,documents:true,analytics:false,cards:false,expenses:false,reports:false,limits:false,users:false,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:false,webhooks:false,payouts:false},supportTier:"standard"},
{code:"PARTNER_TEAM",audience:"PARTNER",title:"Partner Team",shortTitle:"Team",monthlyPrice:8900,yearlyPrice:89000,yearlyDiscountText:"-17% yearly",description:"Small partner teams",bullets:["Multi-user","Basic payouts"],limits:{users:5,apiCallsPerMonth:80000},modules:{dashboard:true,documents:true,analytics:true,cards:false,expenses:false,reports:true,limits:true,users:true,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:false,webhooks:true,payouts:true},supportTier:"standard"},
{code:"PARTNER_AGENCY",audience:"PARTNER",title:"Partner Agency",shortTitle:"Agency",isFeatured:true,badge:"Recommended",monthlyPrice:13900,yearlyPrice:139000,yearlyDiscountText:"-17% yearly",description:"Agency scale",bullets:["Advanced payouts","API"],limits:{users:20,apiCallsPerMonth:200000},modules:{dashboard:true,documents:true,analytics:true,cards:false,expenses:false,reports:true,limits:true,users:true,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:true,webhooks:true,payouts:true},supportTier:"priority"},
{code:"PARTNER_SCALE",audience:"PARTNER",title:"Partner Scale",shortTitle:"Scale",monthlyPrice:23900,yearlyPrice:239000,yearlyDiscountText:"-17% yearly",description:"Large partner operations",bullets:["High volume","CRM export"],limits:{users:60,apiCallsPerMonth:600000},modules:{dashboard:true,documents:true,analytics:true,cards:false,expenses:false,reports:true,limits:true,users:true,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:true,webhooks:true,payouts:true,crmExport:true},supportTier:"priority"},
{code:"PARTNER_ENTERPRISE",audience:"PARTNER",title:"Partner Enterprise",shortTitle:"Enterprise",isEnterprise:true,monthlyPrice:null,yearlyPrice:null,yearlyDiscountText:"Custom contract",description:"Strategic partners",bullets:["White-label","Dedicated support","Custom limits"],limits:{users:null,apiCallsPerMonth:null},modules:{dashboard:true,documents:true,analytics:true,cards:false,expenses:false,reports:true,limits:true,users:true,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:true,webhooks:true,payouts:true,whiteLabel:true,crmExport:true},supportTier:"dedicated"}
];
export const getPlansByAudience=(audience:SubscriptionAudience)=>SUBSCRIPTION_CATALOG.filter((p)=>p.audience===audience);
export const getPlanByCode=(code?:string|null)=>SUBSCRIPTION_CATALOG.find((p)=>p.code===code);
export type SubscriptionEntitlementSnapshot={planCode:SubscriptionPlanCode|null;state:SubscriptionState;modules:SubscriptionPlan["modules"];limits:SubscriptionPlan["limits"]};
const EMPTY_MODULES: SubscriptionPlan["modules"]={dashboard:false,documents:false,analytics:false,cards:false,expenses:false,reports:false,limits:false,users:false,fleet:false,logistics:false,stationsMap:false,support:true,apiAccess:false,webhooks:false};
export const resolveEntitlements=(planCode:string|null|undefined,state:SubscriptionState):SubscriptionEntitlementSnapshot=>{const plan=getPlanByCode(planCode);const enabled=state==="ACTIVE"||state==="TRIAL_ACTIVE";return{planCode:(plan?.code as SubscriptionPlanCode|undefined)??null,state,modules:enabled&&plan?plan.modules:EMPTY_MODULES,limits:enabled&&plan?plan.limits:{}}};
