from __future__ import annotations

from app.models.audit_log import AuditVisibility
from app.services.audit_service import AuditService, RequestContext


CRM_CLIENT_CREATED = "CRM_CLIENT_CREATED"
CRM_CLIENT_UPDATED = "CRM_CLIENT_UPDATED"
CRM_CONTRACT_UPDATED = "CRM_CONTRACT_UPDATED"
CRM_CONTRACT_ACTIVATED = "CRM_CONTRACT_ACTIVATED"
CRM_CONTRACT_PAUSED = "CRM_CONTRACT_PAUSED"
CRM_CONTRACT_TERMINATED = "CRM_CONTRACT_TERMINATED"
CRM_CONTRACT_VERSION_BUMPED = "CRM_CONTRACT_VERSION_BUMPED"
CRM_FEATURE_ENABLED = "CRM_FEATURE_ENABLED"
CRM_FEATURE_DISABLED = "CRM_FEATURE_DISABLED"
CRM_PROFILE_APPLIED = "CRM_PROFILE_APPLIED"
CRM_SUBSCRIPTION_CHARGE_CREATED = "CRM_SUBSCRIPTION_CHARGE_CREATED"
CRM_SUBSCRIPTION_BILLED = "CRM_SUBSCRIPTION_BILLED"
CRM_SUBSCRIPTION_BILLING_RUN = "CRM_SUBSCRIPTION_BILLING_RUN"
CRM_LEAD_CREATED = "CRM_LEAD_CREATED"
CRM_LEAD_QUALIFIED = "CRM_LEAD_QUALIFIED"
CRM_DEAL_STAGE_CHANGED = "CRM_DEAL_STAGE_CHANGED"
CRM_TASK_CREATED = "CRM_TASK_CREATED"
CRM_TASK_UPDATED = "CRM_TASK_UPDATED"
CRM_SUBSCRIPTION_UPDATED = "CRM_SUBSCRIPTION_UPDATED"
ONBOARDING_STATE_CHANGED = "ONBOARDING_STATE_CHANGED"
ONBOARDING_ACTION_APPLIED = "ONBOARDING_ACTION_APPLIED"
ONBOARDING_BLOCKED = "ONBOARDING_BLOCKED"
SUBSCRIPTION_BILLING_RUN_STARTED = "SUBSCRIPTION_BILLING_RUN_STARTED"
SUBSCRIPTION_CHARGES_COMPUTED = "SUBSCRIPTION_CHARGES_COMPUTED"
SUBSCRIPTION_INVOICE_CREATED = "SUBSCRIPTION_INVOICE_CREATED"
SUBSCRIPTION_INVOICE_ISSUED = "SUBSCRIPTION_INVOICE_ISSUED"
SUBSCRIPTION_BILLING_RUN_COMPLETED = "SUBSCRIPTION_BILLING_RUN_COMPLETED"


def audit_event(
    db,
    *,
    event_type: str,
    entity_type: str,
    entity_id: str,
    payload: dict,
    request_ctx: RequestContext | None,
) -> None:
    AuditService(db).audit(
        event_type=event_type,
        entity_type=entity_type,
        entity_id=entity_id,
        action=event_type,
        visibility=AuditVisibility.INTERNAL,
        after=payload,
        request_ctx=request_ctx,
    )


__all__ = [
    "CRM_CLIENT_CREATED",
    "CRM_CLIENT_UPDATED",
    "CRM_CONTRACT_UPDATED",
    "CRM_CONTRACT_ACTIVATED",
    "CRM_CONTRACT_PAUSED",
    "CRM_CONTRACT_TERMINATED",
    "CRM_CONTRACT_VERSION_BUMPED",
    "CRM_FEATURE_ENABLED",
    "CRM_FEATURE_DISABLED",
    "CRM_PROFILE_APPLIED",
    "CRM_SUBSCRIPTION_CHARGE_CREATED",
    "CRM_SUBSCRIPTION_BILLED",
    "CRM_SUBSCRIPTION_BILLING_RUN",
    "CRM_LEAD_CREATED",
    "CRM_LEAD_QUALIFIED",
    "CRM_DEAL_STAGE_CHANGED",
    "CRM_TASK_CREATED",
    "CRM_TASK_UPDATED",
    "CRM_SUBSCRIPTION_UPDATED",
    "ONBOARDING_STATE_CHANGED",
    "ONBOARDING_ACTION_APPLIED",
    "ONBOARDING_BLOCKED",
    "SUBSCRIPTION_BILLING_RUN_STARTED",
    "SUBSCRIPTION_CHARGES_COMPUTED",
    "SUBSCRIPTION_INVOICE_CREATED",
    "SUBSCRIPTION_INVOICE_ISSUED",
    "SUBSCRIPTION_BILLING_RUN_COMPLETED",
    "audit_event",
]
