from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from io import BytesIO

from openpyxl import Workbook
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas


@dataclass(frozen=True)
class DocumentPayload:
    pdf_bytes: bytes | None
    xlsx_bytes: bytes


class DocumentsGenerator:
    def generate_invoice(
        self,
        *,
        invoice_id: str,
        client_id: str,
        period_from: date,
        period_to: date,
        include_pdf: bool = True,
    ) -> DocumentPayload:
        title = f"Invoice {invoice_id}"
        return self._render(
            title=title,
            client_id=client_id,
            period_from=period_from,
            period_to=period_to,
            include_pdf=include_pdf,
        )

    def generate_act(
        self,
        *,
        client_id: str,
        period_from: date,
        period_to: date,
        include_pdf: bool = True,
    ) -> DocumentPayload:
        title = "Act of services"
        return self._render(
            title=title,
            client_id=client_id,
            period_from=period_from,
            period_to=period_to,
            include_pdf=include_pdf,
        )

    def generate_reconciliation_act(
        self,
        *,
        client_id: str,
        period_from: date,
        period_to: date,
        include_pdf: bool = True,
    ) -> DocumentPayload:
        title = "Reconciliation act"
        return self._render(
            title=title,
            client_id=client_id,
            period_from=period_from,
            period_to=period_to,
            include_pdf=include_pdf,
        )

    def _render(
        self,
        *,
        title: str,
        client_id: str,
        period_from: date,
        period_to: date,
        include_pdf: bool,
    ) -> DocumentPayload:
        pdf_bytes = None
        if include_pdf:
            pdf_bytes = self._render_pdf(
                title=title,
                client_id=client_id,
                period_from=period_from,
                period_to=period_to,
            )
        xlsx_bytes = self._render_xlsx(title=title, client_id=client_id, period_from=period_from, period_to=period_to)
        return DocumentPayload(pdf_bytes=pdf_bytes, xlsx_bytes=xlsx_bytes)

    @staticmethod
    def _render_pdf(*, title: str, client_id: str, period_from: date, period_to: date) -> bytes:
        buffer = BytesIO()
        pdf = canvas.Canvas(buffer, pagesize=A4)
        width, height = A4
        pdf.setFont("Helvetica-Bold", 14)
        pdf.drawString(20 * mm, height - 25 * mm, title)
        pdf.setFont("Helvetica", 11)
        pdf.drawString(20 * mm, height - 40 * mm, f"Client: {client_id}")
        pdf.drawString(20 * mm, height - 50 * mm, f"Period: {period_from} — {period_to}")
        pdf.drawString(20 * mm, height - 65 * mm, "Generated by NEFT document service")
        pdf.showPage()
        pdf.save()
        return buffer.getvalue()

    @staticmethod
    def _render_xlsx(*, title: str, client_id: str, period_from: date, period_to: date) -> bytes:
        workbook = Workbook()
        sheet = workbook.active
        sheet.title = "Document"
        sheet.append(["Title", title])
        sheet.append(["Client", client_id])
        sheet.append(["Period", f"{period_from} — {period_to}"])
        sheet.append(["Generated by", "NEFT document service"])

        output = BytesIO()
        workbook.save(output)
        return output.getvalue()
