from __future__ import annotations

from app.models.documents import DocumentType


def build_document_html_template(document_type: DocumentType) -> str:
    title = _title_for_document(document_type)
    return f"""
<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"utf-8\" />
    <style>
      body {{ font-family: Arial, sans-serif; margin: 40px; color: #111; }}
      h1 {{ font-size: 20px; margin-bottom: 12px; }}
      .meta {{ margin-bottom: 16px; }}
      .meta div {{ margin-bottom: 4px; }}
      footer {{ margin-top: 32px; font-size: 12px; color: #666; }}
    </style>
  </head>
  <body>
    <h1>{title}</h1>
    <div class=\"meta\">
      <div><strong>Client:</strong> {{ client_id }}</div>
      <div><strong>Period:</strong> {{ period_from }} — {{ period_to }}</div>
      {% if invoice_id %}
      <div><strong>Invoice:</strong> {{ invoice_id }}</div>
      {% endif %}
    </div>
    <footer>Generated by NEFT document service</footer>
  </body>
</html>
""".strip()


def _title_for_document(document_type: DocumentType) -> str:
    if document_type == DocumentType.INVOICE:
        return "Invoice"
    if document_type == DocumentType.ACT:
        return "Act of services"
    if document_type == DocumentType.RECONCILIATION_ACT:
        return "Reconciliation act"
    return "Document"


__all__ = ["build_document_html_template"]
