from __future__ import annotations

MEMORY_WINDOW_DAYS = 90
HALF_LIFE_DAYS = 30
MIN_SAMPLE_SIZE = 5

COOLDOWN_DAYS = 14
MAX_REPEAT = 2
MAX_FAILED_STREAK = 2

COOLDOWN_PENALTY = -0.5

__all__ = [
    "COOLDOWN_DAYS",
    "COOLDOWN_PENALTY",
    "HALF_LIFE_DAYS",
    "MAX_FAILED_STREAK",
    "MAX_REPEAT",
    "MEMORY_WINDOW_DAYS",
    "MIN_SAMPLE_SIZE",
]
