from fastapi import APIRouter, Depends

from app.api.dependencies.admin import require_admin_user
from app.routers.admin import (
    accounting_exports,
    accounts,
    billing,
    billing_payment_intakes,
    billing_flows,
    closing_packages,
    client_actions,
    clearing,
    crm,
    dashboard,
    disputes,
    documents,
    decision_memory,
    explain,
    fleet_notifications,
    fleet_control,
    fleet_intelligence,
    fleet_policies,
    fuel,
    fuel_providers,
    what_if,
    integration_monitoring,
    integrations,
    logistics,
    legal_graph,
    limits,
    ledger,
    merchants,
    operations,
    refunds,
    finance,
    reversals,
    reconciliation,
    cases,
    risk_rules,
    unified_rules,
    risk_v5,
    settlement_v1,
    settlements,
    legal_integrations,
    fraud,
    money_flow,
    ops,
    marketplace_contracts,
    marketplace_catalog,
    marketplace_order_sla,
    marketplace_sponsored,
    marketplace_moderation,
    notifications,
    service_bookings,
    audit,
    exports,
    bank_stub,
    erp_stub,
    legal,
    pricing,
    entitlements,
    edo,
    bi_sync,
    commercial,
    revenue,
)

router = APIRouter(prefix="/v1/admin", tags=["admin"], dependencies=[Depends(require_admin_user)])

router.include_router(accounts.router)
router.include_router(limits.router)
router.include_router(operations.router)
router.include_router(dashboard.router)
router.include_router(merchants.router)
router.include_router(clearing.router)
router.include_router(accounting_exports.router)
router.include_router(billing.router)
router.include_router(billing_payment_intakes.router)
router.include_router(billing_flows.router)
router.include_router(closing_packages.router)
router.include_router(risk_rules.router)
router.include_router(unified_rules.router)
router.include_router(risk_v5.router)
router.include_router(integration_monitoring.router)
router.include_router(integrations.router)
router.include_router(settlement_v1.router)
router.include_router(settlements.router)
router.include_router(refunds.router)
router.include_router(reversals.router)
router.include_router(disputes.router)
router.include_router(finance.router)
router.include_router(ledger.router)
router.include_router(fuel.router)
router.include_router(fuel_providers.router)
router.include_router(logistics.router)
router.include_router(client_actions.router)
router.include_router(documents.router)
router.include_router(decision_memory.router)
router.include_router(cases.router)
router.include_router(legal_integrations.router)
router.include_router(legal_graph.router)
router.include_router(crm.router)
router.include_router(fraud.router)
router.include_router(money_flow.router)
router.include_router(explain.router)
router.include_router(fleet_notifications.router)
router.include_router(fleet_control.router)
router.include_router(fleet_intelligence.router)
router.include_router(fleet_policies.router)
router.include_router(what_if.router)
router.include_router(ops.router)
router.include_router(marketplace_contracts.router)
router.include_router(marketplace_catalog.router)
router.include_router(marketplace_moderation.router)
router.include_router(marketplace_order_sla.router)
router.include_router(marketplace_sponsored.router)
router.include_router(service_bookings.router)
router.include_router(audit.router)
router.include_router(exports.router)
router.include_router(notifications.router)
router.include_router(reconciliation.router)
router.include_router(bank_stub.router)
router.include_router(erp_stub.router)
router.include_router(legal.router)
router.include_router(pricing.router)
router.include_router(entitlements.router)
router.include_router(edo.router)
router.include_router(bi_sync.router)
router.include_router(commercial.router)
router.include_router(revenue.router)

__all__ = ["router"]
