from __future__ import annotations

from enum import Enum


class DecisionAction(Enum):
    PAYMENT_AUTHORIZE = "PAYMENT_AUTHORIZE"
    PAYMENT_CAPTURE = "PAYMENT_CAPTURE"
    INVOICE_ISSUE = "INVOICE_ISSUE"
    INVOICE_ADJUST = "INVOICE_ADJUST"
    CREDIT_NOTE_CREATE = "CREDIT_NOTE_CREATE"
    PAYOUT_EXPORT = "PAYOUT_EXPORT"
    ACCOUNTING_EXPORT = "ACCOUNTING_EXPORT"
    DOCUMENT_FINALIZE = "DOCUMENT_FINALIZE"


DECISION_ENGINE_VERSION = "v1"
