from __future__ import annotations

from enum import Enum


class DecisionAction(Enum):
    PAYMENT_AUTHORIZE = "PAYMENT_AUTHORIZE"
    PAYMENT_CAPTURE = "PAYMENT_CAPTURE"
    INVOICE_ISSUE = "INVOICE_ISSUE"
    INVOICE_ADJUST = "INVOICE_ADJUST"
    CREDIT_NOTE_CREATE = "CREDIT_NOTE_CREATE"
    PAYOUT_EXPORT = "PAYOUT_EXPORT"
    ACCOUNTING_EXPORT = "ACCOUNTING_EXPORT"
    DOCUMENT_FINALIZE = "DOCUMENT_FINALIZE"
    DOCUMENT_SEND_FOR_SIGNING = "DOCUMENT_SEND_FOR_SIGNING"
    DOCUMENT_FINALIZE_WITH_SIGNATURE = "DOCUMENT_FINALIZE_WITH_SIGNATURE"
    DOCUMENT_VOID_AFTER_SIGNING = "DOCUMENT_VOID_AFTER_SIGNING"


DECISION_ENGINE_VERSION = "v1"
