from __future__ import annotations

from app.models.fleet_intelligence_actions import FIActionCode


DEFAULT_WINDOW_DAYS = 90
CONFIDENCE_SATURATION_COUNT = 120
CONFIDENCE_HALF_LIFE_DAYS = 90

BENCHMARK_BONUS_THRESHOLD = 0.7
BENCHMARK_PENALTY_THRESHOLD = 0.3
BENCHMARK_BONUS_MULTIPLIER = 1.1
BENCHMARK_PENALTY_MULTIPLIER = 0.9

DEFAULT_ACTION_CODES = [
    FIActionCode.SUGGEST_RESTRICT_NIGHT_FUELING.value,
    FIActionCode.SUGGEST_EXCLUDE_STATION_FROM_ROUTES.value,
    FIActionCode.SUGGEST_REQUIRE_ROUTE_LINKED_REFUEL.value,
]

ACTION_LABELS = {
    FIActionCode.SUGGEST_RESTRICT_NIGHT_FUELING.value: "RESTRICT_NIGHT_FUELING",
    FIActionCode.SUGGEST_EXCLUDE_STATION_FROM_ROUTES.value: "EXCLUDE_STATION_FROM_ROUTES",
    FIActionCode.SUGGEST_REQUIRE_ROUTE_LINKED_REFUEL.value: "ADJUST_ROUTE",
}

__all__ = [
    "ACTION_LABELS",
    "BENCHMARK_BONUS_MULTIPLIER",
    "BENCHMARK_BONUS_THRESHOLD",
    "BENCHMARK_PENALTY_MULTIPLIER",
    "BENCHMARK_PENALTY_THRESHOLD",
    "CONFIDENCE_HALF_LIFE_DAYS",
    "CONFIDENCE_SATURATION_COUNT",
    "DEFAULT_ACTION_CODES",
    "DEFAULT_WINDOW_DAYS",
]
