from __future__ import annotations

from enum import Enum


class InsightType(str, Enum):
    DRIVER_BEHAVIOR = "DRIVER_BEHAVIOR"
    VEHICLE_EFFICIENCY = "VEHICLE_EFFICIENCY"
    STATION_TRUST = "STATION_TRUST"


class ActionHintCode(str, Enum):
    RESTRICT_NIGHT_FUELING = "RESTRICT_NIGHT_FUELING"
    REQUIRE_ROUTE_LINKED_REFUEL = "REQUIRE_ROUTE_LINKED_REFUEL"
    REVIEW_DRIVER_BEHAVIOR = "REVIEW_DRIVER_BEHAVIOR"
    CHECK_VEHICLE_FUEL_EFFICIENCY = "CHECK_VEHICLE_FUEL_EFFICIENCY"
    EXCLUDE_STATION_FROM_ROUTES = "EXCLUDE_STATION_FROM_ROUTES"
    MOVE_STATION_TO_WATCHLIST = "MOVE_STATION_TO_WATCHLIST"
    REQUEST_COMPLIANCE_REVIEW = "REQUEST_COMPLIANCE_REVIEW"


class PolicyHintCode(str, Enum):
    DRIVER_BEHAVIOR_HIGH = "DRIVER_BEHAVIOR_HIGH"
    STATION_TRUST_LOW = "STATION_TRUST_LOW"


__all__ = ["InsightType", "ActionHintCode", "PolicyHintCode"]
