export const commercialOrgCopy = {
  errors: {
    loadLog: "Failed to load commercial org state",
    load: "Failed to load commercial state.",
    invalidOrg: "Enter a valid org ID.",
    changePlanLog: "Failed to change commercial plan",
    changePlan: "Failed to change the commercial plan.",
    addonLog: "Failed to update commercial add-on",
    addon: "Failed to update the add-on.",
    overrideLog: "Failed to upsert commercial override",
    override: "Failed to apply the override.",
    overrideReason: "Provide a reason and confirm the override before applying it.",
    overrideRemoveLog: "Failed to remove commercial override",
    overrideRemove: "Failed to remove the override.",
    overrideRemoveReason: "Provide a reason and confirm the override removal before continuing.",
    recomputeLog: "Failed to recompute commercial entitlements",
    recompute: "Failed to recompute entitlements.",
  },
  confirm: {
    changePlan: "Change the organization plan?",
    addon: "Update the add-on?",
    override: "Apply the override?",
    overrideRemove: "Remove the override?",
    recompute: "Recompute the entitlements snapshot?",
  },
  page: {
    subtitle: "Single source of truth for commercial access and entitlements.",
    readMode: "Read mode",
    editMode: "Edit mode",
    load: "Load",
    loading: "Loading commercial control",
    errorTitle: "Commercial control is unavailable",
    reloadAction: "Reload org",
    firstUseTitle: "Commercial control is waiting for an org",
    firstUseDescription: "Enter an org ID to open the canonical commercial owner surface.",
    firstUseHint: "The page shows grounded commercial state only after an organization is selected.",
    orgTitle: "Organization",
    orgName: "Name",
    orgStatus: "Status",
    planTitle: "Current plan",
    planCode: "Code",
    planVersion: "Version",
    planStatus: "Status",
    recomputeNote: "Changes take effect after the entitlements snapshot is recomputed.",
    updatePlan: "Update plan",
    addonsEmpty: "No add-ons are configured.",
    updateAddon: "Update add-on",
    overridesEmpty: "No overrides are configured.",
    overrideNote: "Override changes require an explicit reason and confirmation.",
    overrideConfirm: "I confirm the override",
    overrideApply: "Apply override",
    overrideRemoveConfirm: "I confirm the override removal",
    overrideRemoveAction: "Remove override",
    currentSnapshot: "Current snapshot",
    snapshotVersion: "version",
    noSnapshot: "No entitlements snapshot has been computed yet.",
    noDiff: "No entitlement changes were detected.",
  },
} as const;
